# We use C because conda manages our Python vesion
# and running on OS/X dosen't work with Python.
language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

# Configure the build environment. Global varibles are defined for all configurations.
env:
    global:
        - GH_REF=github.com/cadair/dash_doctests.git
        - CONDA_DEPENDENCIES="sunpy sphinx cython"
        - PIP_DEPENDENCIES="doc2dash"
        - PYTHON_VERSION=2.7
        
install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
  - ./build_all.sh

after_success:
  - ./upload_github.sh
